export const bankingModules = [
  {
    id: "overview",
    label: "Overview",
    path: "/correspondent-banking/overview",
    eyebrow: "Mental model",
    title: "What correspondent banking does",
    summary: "Correspondent banking gives one financial institution reach, liquidity, rail access, operations support, and evidence through another financial institution.",
    objectives: [
      "Explain the difference between the respondent bank and the correspondent bank.",
      "Describe why indirect rail access exists.",
      "Trace the high-level path from customer instruction to evidence trail.",
    ],
    concepts: [
      ["Respondent bank", "The institution that owns the customer relationship and uses another bank for rail access, settlement, file exchange, liquidity, or operations support."],
      ["Correspondent bank", "The banker's bank that supplies connectivity, settlement accounts, limits, monitoring, exception handling, and reports."],
      ["Settlement account", "The balance position used to fund outgoing payments, receive incoming activity, and reconcile rail movement."],
      ["Evidence trail", "The combined record of instruction, approval, message, acknowledgement, settlement, posting, and exception events."],
    ],
    details: [
      "Correspondent banking is not just message forwarding. It combines trust, account services, operations controls, compliance obligations, and settlement.",
      "A respondent bank may not connect directly to every rail. The correspondent lets it reach Fedwire, ACH operators, SWIFT corridors, check image partners, or other networks.",
      "The clean mental model is reach plus proof: the correspondent helps the respondent send work outward and return evidence inward.",
    ],
    developerLens: [
      "Model a payment as a lifecycle with many events, not one mutable status string.",
      "Preserve the IDs that let operations connect original instructions to acknowledgements, returns, recalls, and reports.",
      "Keep transport delivery, business acceptance, settlement, and posting as separate signals.",
    ],
    commonMistakes: [
      "Treating the correspondent as a passive pipe instead of a controlled banking service.",
      "Calling a message delivered when the payment has not been accepted, settled, or posted.",
      "Losing the original reference IDs needed for research and exception handling.",
    ],
    diagramIds: ["relationship-map"],
  },
  {
    id: "roles-and-systems",
    label: "Roles & Systems",
    path: "/correspondent-banking/roles-and-systems",
    eyebrow: "Operating model",
    title: "People, systems, and accountabilities",
    summary: "A correspondent banking workflow crosses bank users, operations teams, core systems, payment hubs, compliance controls, rail adapters, and reconciliation teams.",
    objectives: [
      "Identify the main human and system actors.",
      "Know where the system of record changes.",
      "Understand the difference between vendor platforms and payment standards.",
    ],
    concepts: [
      ["Core banking system", "The system of record for accounts, balances, holds, customer postings, general ledger entries, and some approvals."],
      ["Payment hub", "The orchestration layer that validates, routes, serializes, tracks, and reconciles payment work across rails."],
      ["Exception desk", "The operations team and workflow for rejects, returns, recalls, duplicate checks, adjustments, and investigations."],
      ["Fiserv-style platform", "A vendor implementation layer for banking operations. It is not itself a Fedwire, Nacha, ISO, SWIFT, or X9 standard."],
    ],
    details: [
      "A bank user may start a wire in a branch tool, treasury portal, or back-office screen. The payment hub applies rail-specific validation before a message is sent.",
      "Compliance and fraud controls often sit between approval and release. A pass, review, or reject decision must be captured as evidence.",
      "Vendor systems should be described by the business capability they provide: core posting, ACH origination, wire room, item processing, audit reports, or rail adapter.",
    ],
    developerLens: [
      "Separate channel events from payment events. A portal save is not the same as a rail release.",
      "Store approvals and sanctions decisions as immutable audit events.",
      "Do not hard-code vendor names into rail semantics. Rail behavior should be modeled independently from platform implementation.",
    ],
    commonMistakes: [
      "Conflating a vendor workflow with the legal or network payment standard.",
      "Making the core system responsible for every rail-specific state.",
      "Hiding manual operations work outside the auditable payment timeline.",
    ],
    diagramIds: ["platform-placement"],
  },
  {
    id: "payment-rails",
    label: "Payment Rails",
    path: "/correspondent-banking/payment-rails",
    eyebrow: "Rail comparison",
    title: "Pick the rail by settlement, speed, risk, and format",
    summary: "Each rail has a different settlement model, operating schedule, file or message format, and exception pattern.",
    objectives: [
      "Compare Fedwire, ACH, SWIFT CBPR+, FedNow, and check image exchange.",
      "Separate clearing, settlement, and posting.",
      "Know which rails are message-based, batch-based, or image/file-based.",
    ],
    concepts: [
      ["Fedwire", "Domestic high-value USD transfers with real-time gross settlement in Federal Reserve money."],
      ["ACH", "Batch credit and debit clearing through operators such as FedACH and EPN, governed by Nacha rules."],
      ["SWIFT CBPR+", "Cross-border ISO 20022 messaging where settlement depends on correspondent accounts and bank relationships."],
      ["Check image exchange", "Electronic presentment and return of check images, MICR data, endorsements, and cash letter controls."],
    ],
    details: [
      "Fedwire is used when finality and urgency matter. It requires strict validation, release authority, and settlement awareness.",
      "ACH is efficient for recurring, consumer, payroll, vendor, tax, and treasury movement, but returns can arrive after the original processing day.",
      "SWIFT CBPR+ carries messages across banks; the actual money movement depends on correspondent account relationships and corridor practices.",
      "Check image processing is evidence-heavy: image quality, MICR parsing, duplicate detection, endorsements, warranties, and returns all matter.",
    ],
    developerLens: [
      "Rail adapters should expose rail-specific constraints without leaking implementation details across the whole app.",
      "Batch rails need file-level, batch-level, and item-level status.",
      "Real-time rails still need asynchronous status, posting, and reconciliation handling.",
    ],
    commonMistakes: [
      "Choosing a rail based only on speed instead of settlement finality, return risk, cost, and operational controls.",
      "Treating SWIFT message delivery as proof that settlement completed.",
      "Collapsing ACH file acceptance and individual item outcome into one status.",
    ],
    diagramIds: ["fedwire-iso-sequence"],
  },
  {
    id: "iso-20022",
    label: "ISO 20022",
    path: "/correspondent-banking/iso-20022",
    eyebrow: "Message lab",
    title: "ISO 20022 message families",
    summary: "ISO 20022 is the structured message language used by modern payment, cash-management, and investigation workflows.",
    objectives: [
      "Recognize the practical job of pain, pacs, camt, head, and admi.",
      "Understand why rail-specific implementation guides matter.",
      "Trace original IDs through status reports, recalls, and returns.",
    ],
    concepts: [
      ["pain", "Customer-to-bank initiation, status, cancellation, and investigation requests."],
      ["pacs", "Interbank clearing, settlement, credit transfer, direct debit, status, return, and reversal messages."],
      ["camt", "Cash management, statements, debit/credit notifications, recalls, responses, and investigation case messages."],
      ["head.001", "The business application header that carries sender, receiver, service, and routing metadata."],
      ["admi", "Technical acknowledgements and technical rejections."],
    ],
    details: [
      "The schema defines the vocabulary, while a rail usage guide defines what that network permits.",
      "A customer request may start as pain.001, become pacs.008 for interbank movement, produce pacs.002 status, and later involve camt messages for recall or investigation.",
      "Status messages must point back to original message IDs so operations can reconstruct the lifecycle.",
    ],
    developerLens: [
      "Persist message type, business message ID, instruction ID, end-to-end ID, transaction ID, UETR, and original message references where applicable.",
      "Validate against both XSD constraints and rail market-practice constraints.",
      "Represent message-level status separately from payment-level status.",
    ],
    commonMistakes: [
      "Memorizing message names without knowing which business event they support.",
      "Assuming every ISO rail allows every optional ISO field.",
      "Discarding the business application header after parsing the payload.",
    ],
    diagramIds: ["iso-family-map"],
  },
  {
    id: "ach-nacha",
    label: "ACH & Nacha",
    path: "/correspondent-banking/ach-nacha",
    eyebrow: "Batch rail",
    title: "ACH and Nacha operations",
    summary: "ACH processing is built around originators, ODFIs, ACH operators, RDFIs, receivers, file controls, settlement windows, and return rules.",
    objectives: [
      "Read the hierarchy of an ACH file.",
      "Explain ODFI/RDFI responsibilities.",
      "Understand why ACH returns and NOCs are separate operational flows.",
    ],
    concepts: [
      ["Originator", "The party that initiates ACH entries under an agreement with an ODFI."],
      ["ODFI", "The financial institution that warrants and sends entries into the ACH network."],
      ["RDFI", "The financial institution that receives entries and posts them to receiver accounts."],
      ["SEC code", "The standard entry class code that describes the authorization and transaction context, such as PPD, CCD, CTX, WEB, TEL, or IAT."],
    ],
    details: [
      "A Nacha file contains file headers, batch headers, entry detail records, optional addenda, batch controls, and file controls.",
      "Same Day ACH changes settlement timing, but does not remove return handling, authorization evidence, or file balancing requirements.",
      "Returns and notifications of change must be tied back to original entries and surfaced to originators clearly.",
    ],
    developerLens: [
      "Track file ID, batch number, trace number, company ID, SEC code, effective entry date, settlement date, and return code.",
      "Store file-level validation separately from item-level acceptance.",
      "Design ACH imports and reports as idempotent because files and reports may be retransmitted.",
    ],
    commonMistakes: [
      "Treating an accepted ACH file as proof every entry posted successfully.",
      "Ignoring addenda records for CTX or remittance-heavy corporate workflows.",
      "Failing to route returns and NOCs back to the right originator workflow.",
    ],
    diagramIds: ["ach-file-structure", "ach-return-flow"],
  },
  {
    id: "check-image-processing",
    label: "Checks",
    path: "/correspondent-banking/check-image-processing",
    eyebrow: "Image exchange",
    title: "Check image processing",
    summary: "Check processing is a controlled exchange of images, MICR data, endorsements, warranties, cash letters, returns, and adjustments.",
    objectives: [
      "Understand the check image path from capture to presentment.",
      "Know why image quality and duplicate detection matter.",
      "Recognize the role of X9, Check 21, Reg CC, ECCHO, FedForward, and FedReturn.",
    ],
    concepts: [
      ["MICR line", "The machine-readable routing, account, serial, and transaction code information from the check."],
      ["Image cash letter", "A structured electronic package of check image items and controls sent for exchange."],
      ["IQA", "Image Quality Analysis checks that determine whether the image is usable for exchange and legal evidence."],
      ["Adjustment", "A correction workflow for duplicate, encoding, image, amount, or settlement issues."],
    ],
    details: [
      "Modern check processing moves images and data rather than physical paper in most cases.",
      "Front and back images, endorsements, MICR data, item amount, sequence numbers, and cash-letter totals must remain consistent.",
      "Returns and adjustments are operationally distinct: a return moves the item back, while an adjustment corrects an error or imbalance.",
    ],
    developerLens: [
      "Treat check images as evidence assets with retention and access controls.",
      "Store item-level lifecycle states independently from cash-letter transmission states.",
      "Make duplicate detection explainable enough for operations review.",
    ],
    commonMistakes: [
      "Modeling check processing like a simple payment without image evidence.",
      "Skipping image-quality and duplicate checks before exchange.",
      "Mixing return reasons and adjustment reasons into one vague exception field.",
    ],
    diagramIds: ["check-image-presentment"],
  },
  {
    id: "lifecycle-statuses",
    label: "Statuses",
    path: "/correspondent-banking/lifecycle-statuses",
    eyebrow: "Lifecycle design",
    title: "Payment statuses without false certainty",
    summary: "A payment has multiple independent status tracks: instruction, approval, screening, transport, network response, settlement, posting, notification, and reconciliation.",
    objectives: [
      "Separate transport status from business status.",
      "Separate rail settlement from core posting.",
      "Design a lifecycle that can represent returns, recalls, and investigations.",
    ],
    concepts: [
      ["Technical acknowledgement", "Proof the message was received or rejected at a technical layer."],
      ["Business acceptance", "Proof the network or counterparty accepted the payment instruction for business processing."],
      ["Settlement", "The movement or finality of funds between institutions or settlement accounts."],
      ["Core posting", "The customer and general ledger accounting record inside the bank system of record."],
    ],
    details: [
      "A green queue delivery checkmark does not mean funds settled.",
      "A rail may accept a payment while the core posting is still pending.",
      "A return or recall creates another lifecycle connected to the original payment, not just a text note on the original record.",
    ],
    developerLens: [
      "Use append-only events and derive display status from events rather than overwriting the only status field.",
      "Show operators the source of each status: user, core, payment hub, correspondent, rail, report, or reconciliation job.",
      "Store timestamps for both event occurrence and event ingestion.",
    ],
    commonMistakes: [
      "Using one status column for every stage.",
      "Allowing a later transport event to overwrite a more important business failure.",
      "Not preserving rejected and repaired versions of a payment instruction.",
    ],
    diagramIds: ["status-state-machine"],
  },
  {
    id: "exceptions-investigations",
    label: "Exceptions",
    path: "/correspondent-banking/exceptions-investigations",
    eyebrow: "Controlled loops",
    title: "Returns, recalls, investigations, and adjustments",
    summary: "Exception handling is a controlled workflow around the original item, with ownership, references, evidence, accounting treatment, and deadlines.",
    objectives: [
      "Distinguish rejects, returns, reversals, recalls, investigations, and adjustments.",
      "Understand camt.056, camt.029, pacs.004, ACH return codes, NOCs, and check adjustments.",
      "Design exception queues that preserve original references.",
    ],
    concepts: [
      ["Reject", "A payment or file did not pass validation or acceptance and usually did not complete normal processing."],
      ["Return", "Value or an item is sent back through a defined rail process."],
      ["Recall", "A request to cancel or retrieve a payment that has already moved into the network."],
      ["Investigation", "A case workflow for missing, delayed, disputed, or ambiguous payment activity."],
    ],
    details: [
      "ISO recalls commonly involve camt.056 requests and camt.029 responses. If money returns, pacs.004 may carry the return movement.",
      "ACH returns are code-driven and may arrive after the original file was accepted.",
      "Check exceptions include duplicate items, poor images, missing endorsements, late returns, encoding errors, and adjustment claims.",
    ],
    developerLens: [
      "Store exception cases as first-class records linked to original payment, original message, return message, owner, SLA, and resolution.",
      "Do not erase the original payment event chain when a return or recall happens.",
      "Represent accounting outcomes explicitly: no value moved, value returned, value adjusted, or case annotated only.",
    ],
    commonMistakes: [
      "Calling every problem a failure instead of using rail-specific exception types.",
      "Losing ownership and SLA visibility after an item enters research.",
      "Reversing accounting without a clear link to the rail evidence.",
    ],
    diagramIds: ["exception-investigation-loop"],
  },
  {
    id: "risk-controls",
    label: "Risk & Controls",
    path: "/correspondent-banking/risk-controls",
    eyebrow: "Control plane",
    title: "Risk, compliance, liquidity, and approval controls",
    summary: "Correspondent banking systems need controls for sanctions, fraud, limits, dual approval, liquidity, credit exposure, audit logs, and segregation of duties.",
    objectives: [
      "Identify the controls that must run before release.",
      "Understand liquidity checks and credit-line controls.",
      "Know how maker-checker and audit evidence should be represented.",
    ],
    concepts: [
      ["Sanctions screening", "Party, bank, country, and sometimes purpose screening against sanctions and watchlist data."],
      ["Velocity limit", "A control that detects unusual count or amount patterns over a time window."],
      ["Maker-checker", "A segregation-of-duties pattern where one user creates and another user approves."],
      ["Liquidity control", "A balance or credit availability check before rail release or settlement exposure."],
    ],
    details: [
      "Controls should be visible enough for operations to explain why a payment was released, held, or rejected.",
      "Limits can exist by user, customer, account, rail, currency, destination, time window, and correspondent relationship.",
      "Liquidity controls are separate from compliance controls: a clean payment can still be held if the settlement account cannot support it.",
    ],
    developerLens: [
      "Make control decisions immutable events with rule version, input references, outcome, and reviewer where applicable.",
      "Do not let the same actor create, approve, and release high-risk work without explicit policy support.",
      "Build manual review paths that preserve the automated decision and final human decision.",
    ],
    commonMistakes: [
      "Only storing the final approved status without the control evidence.",
      "Treating sanctions, fraud, approval, and liquidity as one generic hold.",
      "Letting retries bypass the original control decision chain.",
    ],
    diagramIds: ["liquidity-controls"],
  },
  {
    id: "reconciliation-reporting",
    label: "Reconciliation",
    path: "/correspondent-banking/reconciliation-reporting",
    eyebrow: "Proof and close",
    title: "Reconciliation and reporting",
    summary: "Reconciliation proves that messages, rail reports, settlement entries, core postings, GL movements, exceptions, and customer notifications agree.",
    objectives: [
      "Know which records must match at end of day.",
      "Understand unmatched item handling.",
      "Design evidence that supports operations, audit, and customer service.",
    ],
    concepts: [
      ["Rail report", "An external report or acknowledgement from Fedwire, ACH operator, SWIFT/correspondent, or image exchange partner."],
      ["Settlement journal", "The accounting record of debit or credit movement at the correspondent or settlement account level."],
      ["Core journal", "Customer account and GL postings in the bank system of record."],
      ["Unmatched item", "A payment, message, entry, image, or journal line that cannot be paired with expected evidence."],
    ],
    details: [
      "Daily close should compare rail activity, correspondent statements, settlement account movement, core postings, and exception queues.",
      "Matched does not always mean clean: a returned item can be matched but still require customer notification or fee handling.",
      "Reports should expose both totals and drill-down evidence for operations review.",
    ],
    developerLens: [
      "Design reconciliation jobs to be repeatable, idempotent, and explainable.",
      "Store match keys and match confidence rather than only a boolean matched flag.",
      "Preserve external report files or parsed report records with business date and source.",
    ],
    commonMistakes: [
      "Balancing totals without item-level traceability.",
      "Overwriting unmatched exceptions when a later report arrives.",
      "Failing to distinguish business date, settlement date, processing date, and ingestion date.",
    ],
    diagramIds: ["reconciliation-evidence-model", "daily-operations-close"],
  },
];

export const moduleNavItems = [
  { id: "index", label: "Home", path: "/correspondent-banking" },
  ...bankingModules.map(({ id, label, path }) => ({ id, label, path })),
  { id: "diagrams", label: "Diagrams", path: "/correspondent-banking/diagrams" },
];

export function getBankingModule(moduleId) {
  return bankingModules.find((module) => module.id === moduleId);
}
