name: Docker Image CI

on:
  push:
    branches: [ "main" ]  # triggers on every commit to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image without cache
      run: |
        docker build . \
          --file Dockerfile \
          --tag elijahred23/chat-book-site-api:0.0.34 \
          --no-cache

    - name: Push Docker image
      run: docker push elijahred23/chat-book-site-api:0.0.34

