name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and tag the Docker image
      run: docker build . --file Dockerfile --tag elijahred23/chat-book-site-api:0.0.28

    - name: Push Docker image to Docker Hub
      run: docker push elijahred23/chat-book-site-api:0.0.28
